### ISSUE TITLE
Returning Vector instead of Lidar data

### ISSUE THREAD

**Issue by jozphlp** [philwilkes/ea_lidar#1]
Hi, 
Thanks for making this available. I am using your package to get data but I am getting this error:

using FIREFOX
...waiting for page to load
...waiting for shapefile to load
...waiting for available products to load
Traceback (most recent call last):
  File "/home/joseph/Downloads/Software/EA_lidar/ea_lidar/ea_lidar.py", line 253, in <module>
    driver = download_tile(zipPath,
  File "/home/joseph/Downloads/Software/EA_lidar/ea_lidar/ea_lidar.py", line 78, in download_tile
    wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "#productSelect")))
  File "/home/joseph/miniconda3/envs/api/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

Could you provide some guidance on how to solve it? 

Thanks in advance

**Comment by philwilkes** [comment]
Hi @jozphlp can you post the command you used and are you running headless?
